Repository K-Bulkup/Backend, pull requests merged in 2025-07, with the labels that each got.

#13 Feat : cors 설정 #12
  src/main/java/com/kbulkup/common/config/SecurityConfig.java
Labels: ✨ New Feature

#18 [Feature] #7 : 트레이닝 등록 API 구현
  build.gradle
  src/main/java/com/kbulkup/routine/domain/Routine.java
  src/main/java/com/kbulkup/routine/mapper/RoutineMapper.java
  src/main/java/com/kbulkup/routine/service/RoutineService.java
  src/main/java/com/kbulkup/routine/service/RoutineServiceImpl.java
  src/main/java/com/kbulkup/training/controller/TrainingController.java
  src/main/java/com/kbulkup/training/domain/Training.java
  src/main/java/com/kbulkup/training/dto/TrainerTrainingCreateRequestDTO.java
  src/main/java/com/kbulkup/training/mapper/TrainingMapper.java
  src/main/java/com/kbulkup/training/service/TrainingService.java
  src/main/java/com/kbulkup/training/service/TrainingServiceImpl.java
  src/main/resources/mappers/CourseMapper.xml
  src/main/resources/mappers/RoutineMapper.xml
  src/main/resources/mappers/TrainingMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: ✨ New Feature

#20 [Feature] #6: 루틴 상세 정보 조회 api 구현
  src/main/java/com/kbulkup/common/config/RootConfig.java
  src/main/java/com/kbulkup/routine/controller/TraineeRoutineQueryController.java
  src/main/java/com/kbulkup/routine/dto/TraineeRoutineDetailResponseDTO.java
  src/main/java/com/kbulkup/routine/mapper/TraineeRoutineMapper.java
  src/main/java/com/kbulkup/routine/service/TraineeRoutineQueryService.java
  src/main/java/com/kbulkup/routine/service/TraineeRoutineQueryServiceImpl.java
  src/main/resources/mappers/TraineeRoutineMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: ✨ New Feature

#27 [Fix] : 루틴 상세 페이지 및 일반 로그인 충돌 해결
  database.sql
  src/main/java/com/kbulkup/auth/dto/SignupRequestDTO.java
  src/main/java/com/kbulkup/auth/mapper/AuthMapper.java
  src/main/java/com/kbulkup/auth/service/AuthService.java
  src/main/java/com/kbulkup/auth/service/SignupService.java
  src/main/java/com/kbulkup/common/config/SecurityConfig.java
  src/main/java/com/kbulkup/common/config/ServletConfig.java
  src/main/java/com/kbulkup/common/security/CustomUserDetailsService.java
  src/main/java/com/kbulkup/common/security/JwtTokenProvider.java
  src/main/java/com/kbulkup/common/util/OAuthUtils.java
  src/main/java/com/kbulkup/course/mapper/CourseMapper.java
  src/main/java/com/kbulkup/user/mapper/UserMapper.java
  src/main/resources/application.properties
  src/main/resources/config/db.properties
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/mappers/course/CourseMapper.xml
  src/main/resources/mappers/routine/RoutineMapper.xml
  src/main/resources/mappers/user/UserMapper.xml
Labels: 🐛 Bug Fix

#39 [Feature] : #22 트레이너 마이페이지 API
  src/main/java/com/kbulkup/common/exception/ProfileException.java
  src/main/java/com/kbulkup/common/response/ResponseCode.java
  src/main/java/com/kbulkup/profile/controller/TrainerProfileController.java
  src/main/java/com/kbulkup/profile/domain/TrainerProfile.java
  src/main/java/com/kbulkup/profile/dto/request/TrainerProfileCareerUpdateRequestDTO.java
  src/main/java/com/kbulkup/profile/dto/request/TrainerProfileImageUpdateRequestDTO.java
  src/main/java/com/kbulkup/profile/dto/response/TrainerProfileDetailResponseDTO.java
  src/main/java/com/kbulkup/profile/mapper/TrainerProfileMapper.java
  src/main/java/com/kbulkup/profile/service/TrainerProfileService.java
  src/main/java/com/kbulkup/profile/service/TrainerProfileServiceImpl.java
  src/main/resources/mappers/profile/TrainerProfileMapper.xml
Labels: ✨ New Feature

#35 [Feature] : #32 트레이닝 검색 api 구현
  src/main/java/com/kbulkup/routine/domain/Routine.java
  src/main/java/com/kbulkup/routine/service/RoutineService.java
  src/main/java/com/kbulkup/training/controller/TrainingController.java
  src/main/java/com/kbulkup/training/domain/Training.java
  src/main/java/com/kbulkup/training/dto/request/TrainerTrainingCreateRequestDTO.java
  src/main/java/com/kbulkup/training/dto/request/TrainingSearchListRequestDTO.java
  src/main/java/com/kbulkup/training/dto/response/TrainingSearchListResponseDTO.java
  src/main/java/com/kbulkup/training/mapper/TrainingSearchMapper.java
  src/main/java/com/kbulkup/training/service/TrainingSearchService.java
  src/main/java/com/kbulkup/training/service/TrainingSearchServiceImpl.java
  src/main/java/com/kbulkup/training/service/TrainingService.java
  src/main/java/com/kbulkup/training/service/TrainingServiceImpl.java
  src/main/resources/mappers/training/TrainingSearchMapper.xml
Labels: ✨ New Feature

#38 [Refactor] : #37 Enum, @Data,@Setter 삭제 및 핸들러 추가
  database.sql
  src/main/java/com/kbulkup/auth/domain/LoginType.java
  src/main/java/com/kbulkup/auth/dto/request/LoginRequestDTO.java
  src/main/java/com/kbulkup/auth/dto/request/LogoutRequestDTO.java
  src/main/java/com/kbulkup/auth/dto/request/SignupRequestDTO.java
  src/main/java/com/kbulkup/auth/dto/response/LoginResponseDTO.java
  src/main/java/com/kbulkup/auth/dto/response/LogoutResponseDTO.java
  src/main/java/com/kbulkup/auth/dto/response/SignupResponseDTO.java
  src/main/java/com/kbulkup/auth/exception/AuthException.java
  src/main/java/com/kbulkup/auth/service/AuthServiceImpl.java
  src/main/java/com/kbulkup/common/response/ResponseCode.java
  src/main/java/com/kbulkup/common/security/CustomUserDetails.java
  src/main/java/com/kbulkup/counseling/domain/CounselingStatus.java
  src/main/java/com/kbulkup/counseling/dto/response/TrainerCounselingListResponseDTO.java
  src/main/java/com/kbulkup/user/domain/RoleType.java
  src/main/java/com/kbulkup/user/domain/User.java
  src/main/java/com/kbulkup/user/mapper/UserMapper.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: ♻️ Refactor

#40 [Feature] : #15 채팅 메시지 전송 시간 표시 및 채팅방 중복 생성 방지 기능 구현
  src/main/java/com/kbulkup/auth/service/AuthServiceImpl.java
  src/main/java/com/kbulkup/chat/controller/ChatController.java
  src/main/java/com/kbulkup/chat/domain/ChatMessage.java
  src/main/java/com/kbulkup/common/config/SecurityConfig.java
  src/main/java/com/kbulkup/common/config/WebConfig.java
  src/main/java/com/kbulkup/common/config/WebSocketConfig.java
  src/main/java/com/kbulkup/common/security/JwtTokenProvider.java
  src/main/java/com/kbulkup/counseling/controller/CounselingController.java
  src/main/java/com/kbulkup/counseling/domain/Counseling.java
  src/main/java/com/kbulkup/counseling/dto/request/CounselingCreateRequestDTO.java
  src/main/java/com/kbulkup/counseling/dto/response/CounselingCreateResponseDTO.java
  src/main/java/com/kbulkup/counseling/mapper/CounselingMapper.java
  src/main/java/com/kbulkup/counseling/service/CounselingService.java
  src/main/java/com/kbulkup/counseling/service/CounselingServiceImpl.java
  src/main/java/com/kbulkup/user/controller/UserController.java
  src/main/java/com/kbulkup/user/dto/response/UserResponseDTO.java
  src/main/java/com/kbulkup/user/service/UserService.java
  src/main/java/com/kbulkup/user/service/UserServiceImpl.java
  src/main/resources/mappers/counseling/CounselingMapper.xml
Labels: ✨ New Feature

#49 [Feature] #45 : signup 구현 완료
  src/main/java/com/kbulkup/auth/controller/AuthController.java
  src/main/java/com/kbulkup/auth/dto/request/SignupRequestDTO.java
  src/main/java/com/kbulkup/auth/dto/response/LoginResponseDTO.java
  src/main/java/com/kbulkup/auth/dto/response/SignupResponseDTO.java
  src/main/java/com/kbulkup/auth/service/AuthService.java
  src/main/java/com/kbulkup/auth/service/AuthServiceImpl.java
  src/main/java/com/kbulkup/user/domain/User.java
Labels: ✨ New Feature

#51 [Feature] : 트레이닝의 트레이너 정보 조회 API
  src/main/java/com/kbulkup/training/controller/TrainerController.java
  src/main/java/com/kbulkup/training/dto/response/TrainerDetailResponseDTO.java
  src/main/java/com/kbulkup/training/dto/response/TrainerTrainingSummaryDTO.java
  src/main/java/com/kbulkup/training/dto/response/TrainingTrainerDetailProfileResponseDTO.java
  src/main/java/com/kbulkup/training/mapper/TraineeTrainerMapper.java
  src/main/java/com/kbulkup/training/service/TrainerService.java
  src/main/java/com/kbulkup/training/service/TrainerServiceImpl.java
  src/main/resources/mappers/training/TraineeTrainerMapper.xml
Labels: ✨ New Feature

#52 [Feature] #48: 외부 api와 연동하여 마이데이터 DB 저장
  database.sql
  src/main/java/com/kbulkup/asset/controller/TraineeAssetController.java
  src/main/java/com/kbulkup/asset/domain/Transaction.java
  src/main/java/com/kbulkup/asset/domain/TransactionCategory.java
  src/main/java/com/kbulkup/asset/dto/request/TokenRequestDTO.java
  src/main/java/com/kbulkup/asset/dto/response/ExternalAssetResponseDTO.java
  src/main/java/com/kbulkup/asset/dto/response/ExternalTokenResponseDTO.java
  src/main/java/com/kbulkup/asset/mapper/TraineeAssetMapper.java
  src/main/java/com/kbulkup/asset/service/TraineeAssetService.java
  src/main/java/com/kbulkup/asset/service/TraineeAssetServiceImpl.java
  src/main/java/com/kbulkup/asset/typehandler/TransactionCategoryTypeHandler.java
  src/main/resources/mappers/asset/TraineeAssetMapper.xml
  src/main/resources/mybatis-config.xml
Labels: ✨ New Feature

#55 [Feature] #47 : 결제 후 트레이닝 상세 정보 조회 API
  src/main/java/com/kbulkup/routine/dto/RoutineSummaryResponseDTO.java
  src/main/java/com/kbulkup/routine/dto/TraineeRoutineSummaryResponseDTO.java
  src/main/java/com/kbulkup/training/controller/TrainingController.java
  src/main/java/com/kbulkup/training/dto/response/TrainerDetailResponseDTO.java
  src/main/java/com/kbulkup/training/dto/response/TrainerTrainingSummaryResponseDTO.java
  src/main/java/com/kbulkup/training/dto/response/TrainingDetailResponseDTO.java
  src/main/java/com/kbulkup/training/mapper/TraineeTrainerMapper.java
  src/main/java/com/kbulkup/training/mapper/TraineeTrainingMapper.java
  src/main/java/com/kbulkup/training/service/TraineeTrainingService.java
  src/main/java/com/kbulkup/training/service/TrainerServiceImpl.java
  src/main/resources/mappers/training/TraineeTrainerMapper.xml
  src/main/resources/mappers/training/TraineeTrainingMapper.xml
Labels: ✨ New Feature

#59 [Feature] #15 : 1:1 채팅 기능 구현 (WebSocket, MongoDB, 상대방 프로필 조회 포함)
  build.gradle
  database.sql
  src/main/java/com/kbulkup/chat/controller/ChatController.java
  src/main/java/com/kbulkup/chat/controller/ChatRestController.java
  src/main/java/com/kbulkup/chat/domain/MongoChatMessage.java
  src/main/java/com/kbulkup/chat/dto/ChatMessageDTO.java
  src/main/java/com/kbulkup/chat/dto/ChatSummaryDTO.java
  src/main/java/com/kbulkup/chat/dto/ReadMessageDTO.java
  src/main/java/com/kbulkup/chat/repository/ChatMongoRepository.java
  src/main/java/com/kbulkup/chat/service/ChatService.java
  src/main/java/com/kbulkup/chat/service/ChatServiceImpl.java
  src/main/java/com/kbulkup/common/config/MongoConfig.java
  src/main/java/com/kbulkup/common/config/WebConfig.java
  src/main/java/com/kbulkup/common/exception/UserException.java
  src/main/java/com/kbulkup/common/response/ResponseCode.java
  src/main/java/com/kbulkup/counseling/controller/CounselingController.java
  src/main/java/com/kbulkup/counseling/domain/Counseling.java
  src/main/java/com/kbulkup/counseling/domain/CounselingStatus.java
  src/main/java/com/kbulkup/counseling/dto/request/CounselingCreateRequestDTO.java
  src/main/java/com/kbulkup/counseling/dto/response/CounselingDetailResponseDTO.java
  src/main/java/com/kbulkup/counseling/dto/response/TrainerCounselingListResponseDTO.java
  src/main/java/com/kbulkup/counseling/mapper/CounselingMapper.java
  src/main/java/com/kbulkup/counseling/service/CounselingService.java
  src/main/java/com/kbulkup/counseling/service/CounselingServiceImpl.java
  src/main/java/com/kbulkup/training/mapper/TrainingMapper.java
  src/main/java/com/kbulkup/user/mapper/UserMapper.java
  src/main/resources/mappers/TrainingMapper.xml
  src/main/resources/mappers/counseling/CounselingMapper.xml
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨ New Feature

#60 [Feature] #57 : 트레이니의 트레이닝 탭 전체 목록 조회 API
  src/main/java/com/kbulkup/training/controller/TrainingController.java
  src/main/java/com/kbulkup/training/dto/response/TraineeTrainingListResponseDTO.java
  src/main/java/com/kbulkup/training/mapper/TraineeTrainingMapper.java
  src/main/java/com/kbulkup/training/service/TraineeTrainingService.java
  src/main/resources/mappers/training/TraineeTrainingMapper.xml
Labels: ✨ New Feature

#69 [Feature] #17 : 상담 상세 조회 시 상대방 정보 동적 식별 및 응답 구조 개선
  database.sql
  src/main/java/com/kbulkup/common/response/ResponseCode.java
  src/main/java/com/kbulkup/common/security/JwtTokenProvider.java
  src/main/java/com/kbulkup/counseling/controller/CounselingController.java
  src/main/java/com/kbulkup/counseling/dto/response/CounselingListResponseDTO.java
  src/main/java/com/kbulkup/counseling/mapper/CounselingMapper.java
  src/main/java/com/kbulkup/counseling/service/CounselingService.java
  src/main/java/com/kbulkup/counseling/service/CounselingServiceImpl.java
  src/main/resources/mappers/counseling/CounselingMapper.xml
Labels: ✨ New Feature

#72 [Feature] #70 JWT 관련 수정 및 권한 설정
  src/main/java/com/kbulkup/common/config/SecurityConfig.java
  src/main/java/com/kbulkup/common/response/ResponseCode.java
  src/main/java/com/kbulkup/common/security/CustomUserDetailsService.java
  src/main/java/com/kbulkup/common/security/JwtTokenProvider.java
  src/main/java/com/kbulkup/common/security/JwtUtil.java
  src/main/java/com/kbulkup/common/security/SecurityConstants.java
Labels: ✨ New Feature

#74 [Feature] : #73 이벤트 기반 트레이너 프로필 자동 생성 기능 구현
  database.sql
  src/main/java/com/kbulkup/auth/service/AuthServiceImpl.java
  src/main/java/com/kbulkup/profile/listener/TrainerProfileEventListener.java
  src/main/java/com/kbulkup/profile/mapper/TrainerProfileMapper.java
  src/main/java/com/kbulkup/profile/service/TrainerProfileService.java
  src/main/java/com/kbulkup/profile/service/TrainerProfileServiceImpl.java
  src/main/java/com/kbulkup/user/event/UserRegisteredEvent.java
  src/main/java/com/kbulkup/user/event/dto/UserRegisteredEventDataDTO.java
  src/main/resources/mappers/profile/TrainerProfileMapper.xml
Labels: ✨ New Feature

#77 Fix : #76 메서드명 변경
  src/main/java/com/kbulkup/auth/service/AuthServiceImpl.java
Labels: 🐛 Bug Fix

#78 [Feature] #68 : 결제 처리 API
  src/main/java/com/kbulkup/common/config/PortOneConfig.java
  src/main/java/com/kbulkup/common/response/ResponseCode.java
  src/main/java/com/kbulkup/payment/client/PortOneClient.java
  src/main/java/com/kbulkup/payment/controller/TraineeTrainingPaymentController.java
  src/main/java/com/kbulkup/payment/dto/request/TraineeTrainingPaymentRequestDTO.java
  src/main/java/com/kbulkup/payment/dto/response/TraineeTrainingPaymentResponseDTO.java
  src/main/java/com/kbulkup/payment/mapper/TraineeTrainingPaymentMapper.java
  src/main/java/com/kbulkup/payment/service/TraineeTrainingPaymentService.java
  src/main/java/com/kbulkup/payment/service/TraineeTrainingPaymentServiceImpl.java
  src/main/resources/mappers/TraineeTrainingPaymentMapper.xml
Labels: ✨ New Feature
