Repository K-Bulkup/Backend, pull requests merged in 2025-08, with the labels that each got.

#80 [Fix] : database.sql CertType 수정
  database.sql
  src/main/java/com/kbulkup/certificates/dto/request/CertificateCreateRequestDTO.java
Labels: 🐛 Bug Fix

#85 [Feature] : 트레이너에게 자산 데이터 전송
  src/main/java/com/kbulkup/asset/controller/TraineeAssetController.java
  src/main/java/com/kbulkup/asset/mapper/TraineeAssetMapper.java
  src/main/java/com/kbulkup/asset/service/TraineeAssetService.java
  src/main/java/com/kbulkup/asset/service/TraineeAssetServiceImpl.java
  src/main/resources/mappers/asset/TraineeAssetMapper.xml
Labels: ✨ New Feature

#90 [Fix] : 서브모듈 도입으로 인한 PropertySource 수정
  src/main/java/com/kbulkup/common/config/GptConfig.java
  src/main/java/com/kbulkup/gpt/service/GPTServiceImpl.java
Labels: 🐛 Bug Fix

#97 [Fix] #94 : 트레이니 자산 조회 API roomId 타입 Long에서 String으로 수정
  src/main/java/com/kbulkup/asset/controller/TraineeAssetController.java
  src/main/java/com/kbulkup/asset/mapper/TraineeAssetMapper.java
  src/main/java/com/kbulkup/asset/service/TraineeAssetService.java
  src/main/java/com/kbulkup/asset/service/TraineeAssetServiceImpl.java
  src/main/java/com/kbulkup/gpt/GptController.java
  src/main/java/com/kbulkup/gpt/dto/request/ConsultRequestDTO.java
  src/main/java/com/kbulkup/gpt/service/GPTService.java
  src/main/java/com/kbulkup/gpt/service/GPTServiceImpl.java
Labels: 🐛 Bug Fix

#101 [Feature] #99 : 트레이너의 트레이닝 리뷰 조회
  src/main/java/com/kbulkup/review/controller/ReviewController.java
  src/main/java/com/kbulkup/review/dto/response/TrainerTrainingReviewDetailResponseDTO.java
  src/main/java/com/kbulkup/review/mapper/ReviewMapper.java
  src/main/java/com/kbulkup/review/service/ReviewService.java
  src/main/java/com/kbulkup/review/service/ReviewServiceImpl.java
  src/main/resources/mappers/review/ReviewMapper.xml
Labels: ✨ New Feature

#107 [Feature] #43 : 트레이닝 등록 API 연동을 위한 수정
  database.sql
  src/main/java/com/kbulkup/routine/domain/Routine.java
  src/main/java/com/kbulkup/training/controller/TrainingController.java
  src/main/java/com/kbulkup/training/domain/Training.java
  src/main/java/com/kbulkup/training/dto/request/TrainerTrainingCreateRequestDTO.java
  src/main/java/com/kbulkup/training/service/TrainingService.java
  src/main/java/com/kbulkup/training/service/TrainingServiceImpl.java
  src/main/resources/mappers/routine/TrainingRoutineMapper.xml
Labels: ✨ New Feature

#116 [Refactor] #112 : 페이지와 API 연동 후 누락된 기능 추가 및 수정
  src/main/java/com/kbulkup/common/config/PortOneConfig.java
  src/main/java/com/kbulkup/payment/client/PortOneClient.java
  src/main/java/com/kbulkup/payment/mapper/TraineeTrainingPaymentMapper.java
  src/main/java/com/kbulkup/payment/service/TraineeTrainingPaymentServiceImpl.java
  src/main/java/com/kbulkup/routine/dto/RoutineSummaryResponseDTO.java
  src/main/java/com/kbulkup/routine/dto/TraineeRoutineSummaryResponseDTO.java
  src/main/java/com/kbulkup/training/controller/TrainingController.java
  src/main/java/com/kbulkup/training/dto/response/TraineeTrainingListResponseDTO.java
  src/main/java/com/kbulkup/training/mapper/TraineeTrainingMapper.java
  src/main/java/com/kbulkup/training/service/TraineeTrainingService.java
  src/main/resources/mappers/TraineeTrainingPaymentMapper.xml
  src/main/resources/mappers/training/TraineeTrainingMapper.xml
  src/main/resources/mappers/training/TrainingSearchMapper.xml
Labels: ♻️ Refactor

#113 Refactor : 핀테크이용번호 사용해서 자산 데이터 가져오기
  src/main/java/com/kbulkup/asset/service/TraineeAssetServiceImpl.java
Labels: ✨ New Feature

#123 [Feature] #118 : AI 채팅 자산 관련 질문 유도하기 위한 프롬프트 추가 및 프로필 조회 API 개발
  src/main/java/com/kbulkup/common/config/SecurityConfig.java
  src/main/java/com/kbulkup/common/util/PromptBuilder.java
  src/main/java/com/kbulkup/counseling/dto/response/CounselingDetailResponseDTO.java
  src/main/java/com/kbulkup/counseling/service/CounselingServiceImpl.java
Labels: ✨ New Feature

#121 Fix : AUTO_INCREMENT 적용
  database.sql
  src/main/resources/mappers/asset/TraineeAssetMapper.xml
Labels: 🐛 Bug Fix

#126 [Feature] : QnA 기능 개발 #122
  src/main/java/com/kbulkup/common/exception/QnAException.java
  src/main/java/com/kbulkup/common/response/ResponseCode.java
  src/main/java/com/kbulkup/qna/controller/QnAController.java
  src/main/java/com/kbulkup/qna/dto/request/TraineeTrainingQnARequestDTO.java
  src/main/java/com/kbulkup/qna/dto/request/TrainerTrainingQnARequestDTO.java
  src/main/java/com/kbulkup/qna/dto/response/CommonTrainingQnAListResponseDTO.java
  src/main/java/com/kbulkup/qna/mapper/QnAMapper.java
  src/main/java/com/kbulkup/qna/service/QnAService.java
  src/main/java/com/kbulkup/qna/service/QnAServiceImpl.java
  src/main/resources/mappers/qna/QnAMapper.xml
Labels: ✨ New Feature

#130 [Refactor] : 리뷰 개선
  src/main/java/com/kbulkup/review/mapper/ReviewMapper.java
  src/main/java/com/kbulkup/training/service/TraineeTrainingService.java
  src/main/resources/mappers/review/ReviewMapper.xml
Labels: ♻️ Refactor

#131 [Feature] #125 : 관리자 페이지 유저 통계 추가
  src/main/java/com/kbulkup/admin/controller/AdminController.java
  src/main/java/com/kbulkup/admin/controller/AdminPaymentController.java
  src/main/java/com/kbulkup/admin/controller/AdminStatisticsController.java
  src/main/java/com/kbulkup/admin/controller/AdminTrainingController.java
  src/main/java/com/kbulkup/admin/controller/AdminUserController.java
  src/main/java/com/kbulkup/admin/dto/request/AdminPaymentRequestDTO.java
  src/main/java/com/kbulkup/admin/dto/request/AdminTrainingRequestDTO.java
  src/main/java/com/kbulkup/admin/dto/request/AdminUserRequestDTO.java
  src/main/java/com/kbulkup/admin/dto/response/AdminPaymentResponseDTO.java
  src/main/java/com/kbulkup/admin/dto/response/AdminTrainingResponseDTO.java
  src/main/java/com/kbulkup/admin/dto/response/AdminUserResponseDTO.java
  src/main/java/com/kbulkup/admin/dto/response/AdminUserStatisticsResponseDTO.java
  src/main/java/com/kbulkup/admin/dto/response/AdminUserSummaryStatsResponseDTO.java
  src/main/java/com/kbulkup/admin/mapper/AdminPaymentMapper.java
  src/main/java/com/kbulkup/admin/mapper/AdminStatisticsMapper.java
  src/main/java/com/kbulkup/admin/mapper/AdminTrainingMapper.java
  src/main/java/com/kbulkup/admin/service/AdminService.java
  src/main/java/com/kbulkup/admin/service/AdminServiceImpl.java
  src/main/java/com/kbulkup/admin/service/statistics/AdminStatisticsService.java
  src/main/java/com/kbulkup/admin/service/statistics/AdminStatisticsServiceImpl.java
  src/main/java/com/kbulkup/admin/service/training/AdminTrainingService.java
  src/main/java/com/kbulkup/admin/service/training/AdminTrainingServiceImpl.java
  src/main/java/com/kbulkup/admin/service/user/AdminUserService.java
  src/main/java/com/kbulkup/admin/service/user/AdminUserServiceImpl.java
  src/main/java/com/kbulkup/common/exception/AdminException.java
  src/main/java/com/kbulkup/common/response/ResponseCode.java
  src/main/resources/mappers/admin/AdminStatisticsMapper.xml
  src/main/resources/mappers/admin/AdminTrainingMapper.xml
Labels: ✨ New Feature

#137 [Fix] #134 : 루틴 답안 저장되도록 수정
  src/main/java/com/kbulkup/routine/domain/RoutineAnswer.java
  src/main/java/com/kbulkup/training/dto/request/TrainerTrainingCreateRequestDTO.java
  src/main/java/com/kbulkup/training/mapper/TrainingRoutineMapper.java
  src/main/java/com/kbulkup/training/service/TrainingServiceImpl.java
  src/main/resources/mappers/routine/TrainingRoutineMapper.xml
Labels: 🐛 Bug Fix

#133 [Feature] : 리뷰 작성 여부 반환
  src/main/java/com/kbulkup/common/response/ResponseCode.java
  src/main/java/com/kbulkup/qna/service/QnAServiceImpl.java
  src/main/java/com/kbulkup/review/controller/ReviewController.java
  src/main/java/com/kbulkup/review/mapper/ReviewMapper.java
  src/main/java/com/kbulkup/review/service/ReviewService.java
  src/main/java/com/kbulkup/review/service/ReviewServiceImpl.java
  src/main/resources/mappers/review/ReviewMapper.xml
Labels: ✨ New Feature

#142 [Refactor] #141 : 리뷰 조회 API 수정
  src/main/java/com/kbulkup/review/controller/ReviewController.java
Labels: ♻️ Refactor

#143 [Feature] #21 : 루틴 수행처리 API 구현
  database.sql
  src/main/java/com/kbulkup/routine/client/AiJudgeClient.java
  src/main/java/com/kbulkup/routine/controller/RoutineResultController.java
  src/main/java/com/kbulkup/routine/controller/TraineeRoutineController.java
  src/main/java/com/kbulkup/routine/domain/RoutineResult.java
  src/main/java/com/kbulkup/routine/dto/request/RoutineResultCreateRequestDTO.java
  src/main/java/com/kbulkup/routine/dto/response/RoutineResultCreateResponseDTO.java
  src/main/java/com/kbulkup/routine/dto/response/RoutineSummaryResponseDTO.java
  src/main/java/com/kbulkup/routine/dto/response/TraineeRoutineDetailResponseDTO.java
  src/main/java/com/kbulkup/routine/dto/response/TraineeRoutineSummaryResponseDTO.java
  src/main/java/com/kbulkup/routine/mapper/RoutineResultMapper.java
  src/main/java/com/kbulkup/routine/mapper/TraineeRoutineMapper.java
  src/main/java/com/kbulkup/routine/service/RoutineResultService.java
  src/main/java/com/kbulkup/routine/service/RoutineResultServiceImpl.java
  src/main/java/com/kbulkup/routine/service/RoutineService.java
  src/main/java/com/kbulkup/routine/service/RoutineServiceImpl.java
  src/main/java/com/kbulkup/training/controller/TrainingController.java
  src/main/java/com/kbulkup/training/mapper/TraineeTrainingMapper.java
  src/main/java/com/kbulkup/training/service/TraineeTrainingService.java
  src/main/resources/log4j.properties
  src/main/resources/mappers/TraineeRoutineMapper.xml
  src/main/resources/mappers/TraineeTrainingPaymentMapper.xml
  src/main/resources/mappers/routine/RoutineResultMapper.xml
  src/main/resources/mappers/training/TraineeTrainingMapper.xml
Labels: ✨ New Feature

#144 [Feature] #139 : 트레이너 트레이닝 목록 조회 및 검색 API 구현
  src/main/java/com/kbulkup/training/controller/TrainingController.java
  src/main/java/com/kbulkup/training/dto/request/TrainingSearchListRequestDTO.java
  src/main/java/com/kbulkup/training/mapper/TrainingSearchMapper.java
  src/main/java/com/kbulkup/training/service/TrainingSearchService.java
  src/main/java/com/kbulkup/training/service/TrainingSearchServiceImpl.java
  src/main/resources/mappers/training/TrainingSearchMapper.xml
Labels: ✨ New Feature

#149 [Feature] #148 : 트레이너 트레이닝 상세 화면 API구현
  src/main/java/com/kbulkup/training/controller/TrainingController.java
  src/main/java/com/kbulkup/training/dto/request/TrainerTrainingDetailRequestDTO.java
  src/main/java/com/kbulkup/training/dto/response/RoutineCategoryResponseDTO.java
  src/main/java/com/kbulkup/training/dto/response/TrainerTrainingDetailResponseDTO.java
  src/main/java/com/kbulkup/training/mapper/TrainerTrainingMapper.java
  src/main/java/com/kbulkup/training/service/TrainerTrainingService.java
  src/main/resources/mappers/training/TrainerTrainingMapper.xml
Labels: ✨ New Feature

#154 [Refactor] #152 : 트레이너 트레이닝 조회 API에 승인 상태 추가
  src/main/java/com/kbulkup/training/dto/response/TrainingSearchListResponseDTO.java
  src/main/resources/mappers/training/TrainingSearchMapper.xml
Labels: ♻️ Refactor

#157 [Refactor] : 자산 최근 3개월 불러오기
  src/main/java/com/kbulkup/asset/controller/TraineeAssetController.java
  src/main/java/com/kbulkup/asset/dto/request/FintechAuthRequestDTO.java
  src/main/java/com/kbulkup/asset/dto/response/ExternalAccessTokenResponseDTO.java
  src/main/java/com/kbulkup/asset/mapper/TraineeAssetMapper.java
  src/main/java/com/kbulkup/asset/service/TraineeAssetService.java
  src/main/java/com/kbulkup/asset/service/TraineeAssetServiceImpl.java
  src/main/resources/mappers/asset/TraineeAssetMapper.xml
Labels: ♻️ Refactor

#164 [Feature] # 153 : 트레이닝 상태 조회 API 추가 및 AI 컨설팅 프롬프트 개선
  src/main/java/com/kbulkup/common/util/PromptBuilder.java
  src/main/java/com/kbulkup/counseling/mapper/CounselingMapper.java
  src/main/java/com/kbulkup/gpt/service/GPTServiceImpl.java
  src/main/java/com/kbulkup/review/controller/ReviewController.java
  src/main/java/com/kbulkup/review/service/ReviewService.java
  src/main/java/com/kbulkup/review/service/ReviewServiceImpl.java
  src/main/java/com/kbulkup/training/controller/CommonTrainingController.java
  src/main/java/com/kbulkup/training/controller/TraineeTrainingController.java
  src/main/java/com/kbulkup/training/controller/TrainerTrainingController.java
  src/main/java/com/kbulkup/training/dto/response/TraineeTrainingStatusResponseDTO.java
  src/main/java/com/kbulkup/training/service/TraineeTrainingStatusService.java
  src/main/java/com/kbulkup/training/service/TraineeTrainingStatusServiceImpl.java
  src/main/resources/mappers/counseling/CounselingMapper.xml
Labels: ✨ New Feature

#169 [Refactor] OX 루틴 수행의 경우 AI 사용하지 않음
  src/main/java/com/kbulkup/common/exception/QuizException.java
  src/main/java/com/kbulkup/common/response/ResponseCode.java
  src/main/java/com/kbulkup/routine/mapper/RoutineResultMapper.java
  src/main/java/com/kbulkup/routine/service/RoutineResultServiceImpl.java
  src/main/resources/mappers/routine/RoutineResultMapper.xml
Labels: ♻️ Refactor

#174 [Refactor] #171 : 결제 로직 수정
  src/main/java/com/kbulkup/payment/client/PortOneClient.java
  src/main/java/com/kbulkup/payment/mapper/AuthUserMapper.java
  src/main/java/com/kbulkup/payment/service/TraineeTrainingPaymentServiceImpl.java
  src/main/java/com/kbulkup/routine/dto/response/TraineeRoutineDetailResponseDTO.java
  src/main/resources/mappers/AuthUserMapper.xml
  src/main/resources/mappers/TraineeRoutineMapper.xml
Labels: ♻️ Refactor

#177 [Refactor] : 트레이니도 트레이닝 정보를 가져올 수 있도록 권한 설정
  src/main/java/com/kbulkup/training/controller/CommonTrainingController.java
  src/main/resources/mappers/training/TrainerTrainingMapper.xml
Labels: ♻️ Refactor

#179 [Refactor] : QnA 작성자 이름 가져오도록 변경
  src/main/java/com/kbulkup/qna/controller/QnAController.java
  src/main/java/com/kbulkup/qna/dto/response/CommonTrainingQnADetailResponseDTO.java
  src/main/resources/mappers/qna/QnAMapper.xml
Labels: ♻️ Refactor

#184 [Refactor] #180 : 트레이니가 트레이너 페이지 확인
  src/main/java/com/kbulkup/profile/controller/TrainerProfileController.java
  src/main/java/com/kbulkup/profile/service/TrainerProfileService.java
  src/main/java/com/kbulkup/profile/service/TrainerProfileServiceImpl.java
  src/main/java/com/kbulkup/training/dto/response/TrainerDetailResponseDTO.java
  src/main/java/com/kbulkup/training/dto/response/TrainerTrainingSummaryResponseDTO.java
  src/main/java/com/kbulkup/training/dto/response/TrainingTrainerDetailProfileResponseDTO.java
  src/main/java/com/kbulkup/training/mapper/TraineeTrainerMapper.java
  src/main/java/com/kbulkup/training/service/TrainerServiceImpl.java
  src/main/resources/mappers/training/TraineeTrainerMapper.xml
Labels: ♻️ Refactor

#181 [Feature] #168 : 1:1 PT 상담 예약 기능 및 스케줄 관리 기능 구현
  database.sql
  src/main/java/com/kbulkup/chat/service/ChatServiceImpl.java
  src/main/java/com/kbulkup/common/exception/CounselingException.java
  src/main/java/com/kbulkup/common/response/ResponseCode.java
  src/main/java/com/kbulkup/common/scheduler/AiChatScheduler.java
  src/main/java/com/kbulkup/common/scheduler/CounselingScheduler.java
  src/main/java/com/kbulkup/counseling/controller/CounselingReservationController.java
  src/main/java/com/kbulkup/counseling/controller/TrainerScheduleController.java
  src/main/java/com/kbulkup/counseling/domain/Counseling.java
  src/main/java/com/kbulkup/counseling/domain/CounselingReservation.java
  src/main/java/com/kbulkup/counseling/domain/ReservationStatus.java
  src/main/java/com/kbulkup/counseling/domain/TrainerSchedule.java
  src/main/java/com/kbulkup/counseling/dto/request/ReservationCreateRequestDTO.java
  src/main/java/com/kbulkup/counseling/dto/request/TrainerScheduleCreateRequestDTO.java
  src/main/java/com/kbulkup/counseling/dto/response/CounselingCreateResponseDTO.java
  src/main/java/com/kbulkup/counseling/dto/response/CounselingReservationResponseDTO.java
  src/main/java/com/kbulkup/counseling/dto/response/ReservationResponseDTO.java
  src/main/java/com/kbulkup/counseling/dto/response/TrainerScheduleResponseDTO.java
  src/main/java/com/kbulkup/counseling/mapper/CounselingMapper.java
  src/main/java/com/kbulkup/counseling/mapper/CounselingReservationMapper.java
  src/main/java/com/kbulkup/counseling/mapper/TrainerScheduleMapper.java
  src/main/java/com/kbulkup/counseling/service/CounselingReservationService.java
  src/main/java/com/kbulkup/counseling/service/CounselingReservationServiceImpl.java
  src/main/java/com/kbulkup/counseling/service/CounselingServiceImpl.java
  src/main/java/com/kbulkup/counseling/service/TrainerScheduleService.java
  src/main/java/com/kbulkup/counseling/service/TrainerScheduleServiceImpl.java
  src/main/java/com/kbulkup/training/service/TraineeTrainingStatusServiceImpl.java
  src/main/resources/mappers/counseling/CounselingMapper.xml
  src/main/resources/mappers/counseling/CounselingReservationMapper.xml
  src/main/resources/mappers/counseling/TrainerScheduleMapper.xml
Labels: ✨ New Feature

#190 [Refactor] #189 : 루틴 수행 처리 로직 수정
  src/main/resources/mappers/review/ReviewMapper.xml
  src/main/resources/mappers/routine/RoutineResultMapper.xml
  src/main/resources/mappers/training/TraineeTrainingMapper.xml
Labels: ♻️ Refactor

#195 [Fix] #168 : 채팅방 관련 테이블 변경으로 인한 쿼리문 수정
  src/main/resources/mappers/asset/TraineeAssetMapper.xml
Labels: 🐛 Bug Fix

#192 [Refactor] #191 : 결제 시 userId를 AuthenticationPrincipal 사용
  src/main/java/com/kbulkup/payment/controller/TraineeTrainingPaymentController.java
  src/main/java/com/kbulkup/payment/service/TraineeTrainingPaymentService.java
  src/main/java/com/kbulkup/payment/service/TraineeTrainingPaymentServiceImpl.java
Labels: ♻️ Refactor

#204 [Refactor] #193 : AI 채점 프롬프트 보완
  src/main/java/com/kbulkup/common/util/PromptBuilder.java
  src/main/java/com/kbulkup/gpt/dto/common/MessageDTO.java
  src/main/java/com/kbulkup/gpt/dto/request/ImageContentDTO.java
Labels: ♻️ Refactor

#216 [Test] #210 : 서비스 레이어 단위 테스트 작성
  build.gradle
  src/test/java/TestSuite.md
  src/test/java/com/kbulkup/admin/service/user/AdminUserServiceImplTest.java
  src/test/java/com/kbulkup/auth/service/AuthServiceImplTest.java
  src/test/java/com/kbulkup/certificates/service/CertificatesServiceImplTest.java
  src/test/java/com/kbulkup/chat/service/ChatServiceImplTest.java
  src/test/java/com/kbulkup/common/security/PasswordEncoderTest.java
  src/test/java/com/kbulkup/gpt/service/GPTServiceImplTest.java
  src/test/java/com/kbulkup/review/service/ReviewServiceImplTest.java
  src/test/java/com/kbulkup/training/service/TrainingServiceImplTest.java
  src/test/java/com/kbulkup/user/service/UserServiceImplTest.java
Labels: ✅ Test
